#!/usr/bin/env php
<?php
require_once "vendor/autoload.php";
$request = (new \Celery\Request())
    ->withMethod("GET");
$handler = new \CurlPsr\Handler();
$urls = array_slice($argv, 1);
//$handler->debug = true;
$responses = $handler->withTimeout(10000)->runSimple(
    ...array_map(
        function($url) use ($request) {
            return $request->withUri(
                (new \Celery\Uri())->withFullUrl($url)
            );
        },
        $urls
    )
);
foreach($responses as $k => $r) {
    $content = "";
    do {
        $c = $r->getBody()->read(1024);
        $content .= $c;
    } while(strlen($c));
    echo "{$urls[$k]}: " . strlen($content);
    if($r->getBody()->getSize() !== null) {
        echo " (finished={$r->getBody()->getSize()})";
    } elseif(!strlen($content)) {
        echo " [{$r->getStatusCode()}] " . json_encode($r->getHeaders());
    }
    echo "\n";
}